version: "3"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./stockwise-be
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./stockwise-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
